services:
  - type: web
    name: mundial2026-predictor
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start:prod"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
